### ISSUE TITLE
Add Validation for Max Words input field

### ISSUE THREAD

**Issue by jatinchawda1503** [jatinchawda1503/CVGen#4]
Max Word input field is attribute type to 'text'. There is need of validation for the text to be as numberic.
Code to be replace
```
<input
  type="text"
  inputmode="numeric"
  pattern="[0-9]"
 class="form-control" 
 id="maxWords" 
 name="maxWords" 
 value="100" 
required
/>
```

**Comment by imrannasrullah** [comment]
I'll handle this!

**Comment by sanibalakrishna** [comment]
@jatinchawda1503 can you assign this issue to me.

**Comment by imrannasrullah** [comment]
> I'll handle this!

^

**Comment by jatinchawda1503** [comment]
@sanibalakrishna, @imrannasrullah  first PR will be only taken into account.
Thanks and happy contributing.
